alter table "public"."last_url" drop constraint "last_url_id_fkey";

create table "public"."schedule" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid not null,
    "start" time without time zone not null,
    "end" time without time zone not null,
    "day" smallint not null
);


alter table "public"."schedule" enable row level security;

alter table "public"."profiles" add column "timezone" text;

CREATE UNIQUE INDEX schedule_pkey ON public.schedule USING btree (id);

alter table "public"."schedule" add constraint "schedule_pkey" PRIMARY KEY using index "schedule_pkey";

alter table "public"."schedule" add constraint "schedule_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."schedule" validate constraint "schedule_user_id_fkey";

create policy "Crud authentification"
on "public"."schedule"
as permissive
for all
to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



